# ------------------------------------------------------------------------------
# Copyright (c) 2025 Jyotirmay Gupta
#
# Project: User Identity Service
# Description: This is a personal project by Jyotirmay Gupta that implements a
# user identity management service using Spring Boot. It provides functionality to
# register and maintain user identities within a system.
#
# This code is intended for educational and personal use, demonstrating core backend
# concepts such as RESTful API design, user registration, integration
# with persistent storage using Spring Boot.
#
# Licensed under the Apache License Version 2.0. See LICENSE file for more details.
# ------------------------------------------------------------------------------

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_identity_db?currentSchema=user_identity_schema
    username: identity_user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # or validate, create, create-drop depending on your needs
    properties:
      hibernate:
        default_schema: user_identity_schema
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082

logging:
  level:
    root: INFO
    com.jyotirmay: INFO